export const libraries = [
  {
    id: 'mui',
    name: 'Material UI',
    short: 'MUI',
    org: 'MUI',
    category: '成品型组件库',
    accent: 'blue',
    summary: '基于 Material Design 的成熟 React 组件库，覆盖通用界面与复杂数据组件生态。',
    fit: ['通用后台', 'SaaS', '数据密集型产品', '快速交付'],
    traits: ['组件覆盖广', '主题系统成熟', '生态完整'],
    caveat: '默认视觉辨识度较强；深度品牌化需要系统性覆盖主题与组件样式。',
    styling: 'Emotion / styled API / tokens',
    license: 'MIT（核心）',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 5, control: 3, accessibility: 4, speed: 5, learning: 3 },
    links: { docs: 'https://mui.com/material-ui/', github: 'https://github.com/mui/material-ui' },
  },
  {
    id: 'antd',
    name: 'Ant Design',
    short: 'Ant',
    org: 'Ant Group',
    category: '成品型组件库',
    accent: 'cyan',
    summary: '面向中后台与企业应用的 React UI 库，表格、表单、弹层和业务反馈组件非常完整。',
    fit: ['企业后台', '运营平台', '管理系统', '复杂表单'],
    traits: ['企业组件丰富', '中文资料充足', '设计规范完整'],
    caveat: '产品容易呈现典型 Ant 风格；移动端与强品牌化场景通常需要额外设计工作。',
    styling: 'CSS-in-JS / Design Token',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 5, control: 3, accessibility: 3, speed: 5, learning: 4 },
    links: { docs: 'https://ant.design/docs/react/introduce/', github: 'https://github.com/ant-design/ant-design' },
  },
  {
    id: 'chakra',
    name: 'Chakra UI',
    short: 'Chakra',
    org: 'Chakra Systems',
    category: '成品型组件库',
    accent: 'teal',
    summary: '强调可组合性、语义化属性和主题令牌的 React 组件库，适合快速构建定制界面。',
    fit: ['产品原型', '中小型 SaaS', '团队设计系统', '响应式界面'],
    traits: ['组合 API 清晰', '主题能力强', '开发体验直接'],
    caveat: '升级大版本时需要认真核对 API；复杂企业组件覆盖不如 MUI、Ant Design。',
    styling: 'Panda / style props / recipes',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 4, control: 4, accessibility: 4, speed: 4, learning: 4 },
    links: { docs: 'https://www.chakra-ui.com/docs/get-started/installation', github: 'https://github.com/chakra-ui/chakra-ui' },
  },
  {
    id: 'mantine',
    name: 'Mantine',
    short: 'Mantine',
    org: 'Mantine',
    category: '成品型组件库',
    accent: 'indigo',
    summary: '组件、Hooks、表单与通知能力覆盖均衡，偏工程实用主义的 React UI 工具箱。',
    fit: ['仪表盘', '内容工具', '内部系统', '独立产品'],
    traits: ['Hooks 丰富', '默认视觉现代', '文档示例完整'],
    caveat: '与其主题和样式体系绑定较深；追求完全无样式底座时不是首选。',
    styling: 'CSS Modules / styles API',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 5, control: 4, accessibility: 4, speed: 5, learning: 4 },
    links: { docs: 'https://mantine.dev/', github: 'https://github.com/mantinedev/mantine' },
  },
  {
    id: 'primereact',
    name: 'PrimeReact',
    short: 'Prime',
    org: 'PrimeTek',
    category: '成品型组件库',
    accent: 'green',
    summary: '以组件数量和企业数据能力见长，提供主题、模板与复杂表格等完整方案。',
    fit: ['数据后台', 'ERP / CRM', '快速企业交付', '重表格应用'],
    traits: ['组件数量多', 'DataTable 强', '主题方案丰富'],
    caveat: 'API 面较大，视觉与包体治理需要规划；部分高级生态可能涉及商业产品。',
    styling: 'Styled / unstyled mode / themes',
    license: 'MIT（核心）',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 5, control: 4, accessibility: 3, speed: 5, learning: 3 },
    links: { docs: 'https://primereact.org/', github: 'https://github.com/primefaces/primereact' },
  },
  {
    id: 'heroui',
    name: 'HeroUI',
    short: 'Hero',
    org: 'HeroUI',
    category: '成品型组件库',
    accent: 'violet',
    summary: '现代视觉取向的 React 组件库，适合产品官网、SaaS 与需要较好默认质感的应用。',
    fit: ['现代 SaaS', '营销与产品结合', '中小型应用', '快速原型'],
    traits: ['默认样式精致', '动效自然', '上手成本低'],
    caveat: '复杂企业组件深度不及老牌库；需要评估样式体系与团队技术约束。',
    styling: 'CSS variables / utility workflow',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: true,
    scores: { completeness: 4, control: 3, accessibility: 4, speed: 5, learning: 4 },
    links: { docs: 'https://heroui.com/en/docs/react/getting-started/quick-start', github: 'https://github.com/heroui-inc/heroui' },
  },
  {
    id: 'radix',
    name: 'Radix Primitives',
    short: 'Radix',
    org: 'WorkOS',
    category: '无样式 / Headless',
    accent: 'slate',
    summary: '低层级、无样式、可访问的 React UI 原语，适合作为自有设计系统的交互底座。',
    fit: ['自建设计系统', '高品牌化产品', '组件平台', '交互复杂控件'],
    traits: ['可访问性基础好', '行为稳定', '样式完全自定义'],
    caveat: '不提供完整视觉与业务组件；团队需承担样式、令牌、组合与维护成本。',
    styling: '完全自定义',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 3, control: 5, accessibility: 5, speed: 3, learning: 3 },
    links: { docs: 'https://www.radix-ui.com/primitives', github: 'https://github.com/radix-ui/primitives' },
  },
  {
    id: 'react-aria',
    name: 'React Aria',
    short: 'Aria',
    org: 'Adobe',
    category: '无样式 / Headless',
    accent: 'orange',
    summary: 'Adobe 提供的无样式组件与 Hooks，重点处理可访问性、国际化和复杂交互状态。',
    fit: ['高可访问性产品', '国际化应用', '设计系统底座', '复杂选择与日期控件'],
    traits: ['可访问性深入', '国际化能力强', '状态与行为解耦'],
    caveat: '概念与组合层次较多；需要较成熟的组件工程和视觉实现能力。',
    styling: '完全自定义',
    license: 'Apache-2.0',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 4, control: 5, accessibility: 5, speed: 3, learning: 2 },
    links: { docs: 'https://react-aria.adobe.com/', github: 'https://github.com/adobe/react-spectrum' },
  },
  {
    id: 'base-ui',
    name: 'Base UI',
    short: 'Base',
    org: 'MUI',
    category: '无样式 / Headless',
    accent: 'blue',
    summary: 'MUI 团队维护的无样式 React 组件集合，面向可访问、可组合、可深度定制的界面。',
    fit: ['定制设计系统', '现代产品界面', '替代重样式库', '组件基础设施'],
    traits: ['无默认视觉', '组合能力强', '与 MUI 生态相邻'],
    caveat: '需要自行构建设计语言；选型时应关注组件成熟度与迁移路径。',
    styling: '完全自定义',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 3, control: 5, accessibility: 5, speed: 3, learning: 3 },
    links: { docs: 'https://base-ui.com/', github: 'https://github.com/mui/base-ui' },
  },
  {
    id: 'ark-ui',
    name: 'Ark UI',
    short: 'Ark',
    org: 'Chakra Systems',
    category: '无样式 / Headless',
    accent: 'amber',
    summary: '基于状态机的跨框架 Headless 组件库，在 React、Vue、Solid、Svelte 间保持行为一致。',
    fit: ['跨框架设计系统', '复杂交互组件', '长期组件平台', '高定制产品'],
    traits: ['状态机驱动', '跨框架一致', '无样式'],
    caveat: '抽象层较高；团队需理解复合组件、状态机和样式架构。',
    styling: '完全自定义',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 4, control: 5, accessibility: 5, speed: 3, learning: 2 },
    links: { docs: 'https://ark-ui.com/', github: 'https://github.com/chakra-ui/ark' },
  },
  {
    id: 'headlessui',
    name: 'Headless UI',
    short: 'Headless',
    org: 'Tailwind Labs',
    category: '无样式 / Headless',
    accent: 'sky',
    summary: '完全无样式的可访问组件集合，API 简洁，尤其适合 Tailwind CSS 工作流。',
    fit: ['Tailwind 项目', '营销站', '中小型产品', '轻量自定义 UI'],
    traits: ['API 直接', '可访问基础', '与 Tailwind 协同'],
    caveat: '组件范围相对克制；非 Tailwind 项目仍可用，但优势会减弱。',
    styling: '完全自定义',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: true,
    scores: { completeness: 2, control: 5, accessibility: 4, speed: 4, learning: 4 },
    links: { docs: 'https://headlessui.com/', github: 'https://github.com/tailwindlabs/headlessui' },
  },
  {
    id: 'shadcn',
    name: 'shadcn/ui',
    short: 'shadcn',
    org: 'shadcn',
    category: '源码分发 / Registry',
    accent: 'neutral',
    summary: '把组件源码复制进项目的分发方式，强调代码所有权、可修改性和 Registry 生态。',
    fit: ['强定制 SaaS', 'AI 辅助开发', '项目内组件库', 'Next.js / Vite'],
    traits: ['源码归项目所有', '生态活跃', '组合方式透明'],
    caveat: '不是传统 npm 组件库；升级、统一治理和重复修改需要团队自行负责，默认工作流偏 Tailwind。',
    styling: 'Tailwind CSS / CSS variables',
    license: 'MIT',
    sourceMode: '复制源码',
    tailwind: true,
    scores: { completeness: 4, control: 5, accessibility: 4, speed: 4, learning: 3 },
    links: { docs: 'https://ui.shadcn.com/docs', github: 'https://github.com/shadcn-ui/ui' },
  },
  {
    id: 'fluent',
    name: 'Fluent UI React',
    short: 'Fluent',
    org: 'Microsoft',
    category: '企业设计系统实现',
    accent: 'azure',
    summary: 'Microsoft Fluent 2 的 React 实现，适合微软生态、生产力工具和桌面感 Web 应用。',
    fit: ['企业软件', 'Microsoft 生态', '生产力工具', 'Web / Electron'],
    traits: ['Fluent 2 语言', '令牌体系', '企业级基础'],
    caveat: '不同代际包与组件覆盖需要辨别；非微软风格产品需要较强主题改造。',
    styling: 'Griffel / design tokens',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 4, control: 4, accessibility: 4, speed: 4, learning: 3 },
    links: { docs: 'https://fluent2.microsoft.design/components/web/react/', github: 'https://github.com/microsoft/fluentui' },
  },
  {
    id: 'carbon',
    name: 'Carbon React',
    short: 'Carbon',
    org: 'IBM',
    category: '企业设计系统实现',
    accent: 'gray',
    summary: 'IBM Carbon Design System 的 React 组件实现，强调严谨的信息结构与企业产品一致性。',
    fit: ['大型企业平台', '数据与运维产品', '跨团队规范', 'B2B 产品'],
    traits: ['规范完整', '信息密度高', '设计开发协同'],
    caveat: '视觉语言鲜明且规则较重；小型产品可能承担不必要的体系成本。',
    styling: 'Sass / tokens',
    license: 'Apache-2.0',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 5, control: 3, accessibility: 4, speed: 4, learning: 2 },
    links: { docs: 'https://carbondesignsystem.com/developing/frameworks/react/', github: 'https://github.com/carbon-design-system/carbon' },
  },
  {
    id: 'spectrum',
    name: 'React Spectrum',
    short: 'Spectrum',
    org: 'Adobe',
    category: '企业设计系统实现',
    accent: 'magenta',
    summary: 'Adobe Spectrum 设计语言的 React 组件层，强调跨设备、可访问性和一致体验。',
    fit: ['创作工具', '专业工作流', '高可访问性应用', 'Adobe 风格产品'],
    traits: ['交互细节完整', '无障碍能力强', '复杂控件成熟'],
    caveat: '视觉与 Adobe 体系绑定明显；完全品牌化更适合使用底层 React Aria。',
    styling: 'Spectrum tokens / style macro',
    license: 'Apache-2.0',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 5, control: 2, accessibility: 5, speed: 4, learning: 2 },
    links: { docs: 'https://react-spectrum.adobe.com/', github: 'https://github.com/adobe/react-spectrum' },
  },
  {
    id: 'primer',
    name: 'Primer React',
    short: 'Primer',
    org: 'GitHub',
    category: '企业设计系统实现',
    accent: 'purple',
    summary: 'GitHub Primer 的 React 组件实现，适合开发者工具、协作平台与代码托管类产品。',
    fit: ['开发者工具', '协作平台', '代码产品', 'GitHub 风格界面'],
    traits: ['开发者产品范式', '语义明确', '设计规范公开'],
    caveat: '部分模式与 GitHub 业务场景高度相关；通用营销产品未必合适。',
    styling: 'Styled System / tokens',
    license: 'MIT',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 4, control: 3, accessibility: 4, speed: 4, learning: 3 },
    links: { docs: 'https://primer.style/product/components/', github: 'https://github.com/primer/react' },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    short: 'Blueprint',
    org: 'Palantir',
    category: '专业应用组件库',
    accent: 'navy',
    summary: '面向桌面式、数据密集型 Web 应用的 React UI 工具包，强调高信息密度与专业操作。',
    fit: ['数据分析工具', '桌面式 Web', '内部专业软件', '复杂控制台'],
    traits: ['密集型界面', '专业控件', '桌面应用感'],
    caveat: '默认视觉偏传统专业软件；移动端和轻量消费产品不是主要方向。',
    styling: 'Sass / CSS',
    license: 'Apache-2.0',
    sourceMode: 'npm 包',
    tailwind: false,
    scores: { completeness: 4, control: 3, accessibility: 3, speed: 4, learning: 3 },
    links: { docs: 'https://blueprintjs.com/', github: 'https://github.com/palantir/blueprint' },
  },
];

export const designSystems = [
  {
    name: 'Material Design 3', owner: 'Google', tone: '动态色彩、层级与适应性',
    idea: '以设计令牌、动态颜色、容器层级和跨设备一致性组织产品视觉。',
    use: 'Android 关联产品、通用消费产品、需要成熟规范的团队。',
    link: 'https://m3.material.io/', accent: 'blue'
  },
  {
    name: 'Ant Design', owner: 'Ant Group', tone: '理性、秩序、企业效率',
    idea: '围绕中后台工作流建立组件、模式、数据展示和反馈规则。',
    use: '管理后台、运营平台、复杂表单与业务系统。',
    link: 'https://ant.design/docs/spec/introduce/', accent: 'cyan'
  },
  {
    name: 'Fluent 2', owner: 'Microsoft', tone: '柔和层次、生产力、跨平台',
    idea: '通过颜色、材质、深度、动效和令牌统一 Microsoft 产品体验。',
    use: '企业工具、桌面感 Web、Microsoft 生态产品。',
    link: 'https://fluent2.microsoft.design/', accent: 'azure'
  },
  {
    name: 'Carbon', owner: 'IBM', tone: '严谨、技术、信息密集',
    idea: '将基础、组件、模式、内容和治理组织成大型企业设计体系。',
    use: 'B2B 平台、数据产品、运维系统、大型组织。',
    link: 'https://carbondesignsystem.com/', accent: 'gray'
  },
  {
    name: 'Spectrum 2', owner: 'Adobe', tone: '创作工具、包容、跨设备',
    idea: '强调可访问、适应输入方式和专业创意工作流的一致交互。',
    use: '创作工具、媒体软件、复杂专业工作流。',
    link: 'https://spectrum.adobe.com/', accent: 'magenta'
  },
  {
    name: 'Primer', owner: 'GitHub', tone: '开发者导向、清晰、协作',
    idea: '用基础令牌、组件和产品模式支撑代码协作与开发者体验。',
    use: '开发平台、代码工具、技术社区与协作产品。',
    link: 'https://primer.style/', accent: 'purple'
  },
  {
    name: 'Polaris', owner: 'Shopify', tone: '商业任务、内容清晰、可信',
    idea: '围绕商家工作流、内容语气、可访问性与跨渠道体验建立规范。',
    use: '电商后台、商家工具、交易与运营产品。',
    link: 'https://polaris.shopify.com/', accent: 'green'
  },
  {
    name: 'Atlassian Design System', owner: 'Atlassian', tone: '协作、工作流、规模化',
    idea: '为复杂协作产品提供令牌、组件、内容和交互模式。',
    use: '项目管理、团队协作、知识与流程产品。',
    link: 'https://atlassian.design/', accent: 'indigo'
  },
];

export const selectionQuestions = {
  product: [
    { value: 'admin', label: '企业后台', hint: '表格、表单、权限、流程' },
    { value: 'saas', label: 'SaaS 产品', hint: '品牌、速度与扩展平衡' },
    { value: 'design-system', label: '自建设计系统', hint: '控制权与长期治理' },
    { value: 'professional', label: '专业工具', hint: '高密度与复杂交互' },
  ],
  control: [
    { value: 'fast', label: '优先快速交付' },
    { value: 'balanced', label: '速度与定制平衡' },
    { value: 'full', label: '优先完全控制' },
  ],
  styling: [
    { value: 'no-tailwind', label: '不使用 Tailwind' },
    { value: 'tailwind-ok', label: '可以使用 Tailwind' },
    { value: 'agnostic', label: '样式方案不限' },
  ],
};

export const principles = [
  { step: '01', title: '先选抽象层，不先选外观', text: '成品库解决交付速度，Headless 解决行为与可访问性，源码分发解决代码所有权，企业设计系统解决组织一致性。' },
  { step: '02', title: '把组件数量换算成业务覆盖', text: '不要只统计 Button 和 Modal。真正拉开差距的是 DataGrid、复杂表单、日期、树、上传、虚拟化和无障碍细节。' },
  { step: '03', title: '评估改造成本而非首屏效果', text: '默认样式好看不代表长期成本低。应验证令牌覆盖、状态样式、暗色模式、密度、国际化和升级策略。' },
  { step: '04', title: '用真实页面做选型样板', text: '选一个包含表格、表单、弹层、空状态和响应式布局的真实页面，同时用两个候选方案实现，再比较代码与维护成本。' },
  { step: '05', title: '设计治理要进入仓库', text: '令牌、组件规范、Storybook、视觉回归、可访问性测试和变更日志必须成为工程资产，而不是只存在于 Figma。' },
];

export const sourceGroups = [
  { title: '成品型组件库', items: ['Material UI', 'Ant Design', 'Chakra UI', 'Mantine', 'PrimeReact', 'HeroUI'] },
  { title: 'Headless 与基础原语', items: ['Radix Primitives', 'React Aria', 'Base UI', 'Ark UI', 'Headless UI'] },
  { title: '源码分发', items: ['shadcn/ui'] },
  { title: '企业设计系统实现', items: ['Fluent UI React', 'Carbon React', 'React Spectrum', 'Primer React', 'Blueprint'] },
];
